### ISSUE TITLE
improving the JS transpiler

### ISSUE THREAD

**Issue by jonathanong** [polyfills/ecstacy#9]
right now there are a lot of issues with the libraries we use. here are a few issues and solutions.
### Esprima development is slow

they don't intend to support ES6 syntax until ES6 is finalized, but that is a little too slow for us. we can switch to acorn, which is supposedly faster: https://github.com/marijnh/acorn

https://gist.github.com/benjamn/2a2843a626bc6b502f77
### Fork all the plugins

There are multiple issues with plugins, mostly that it creates a billion copies of each dependency. I have like 20 of the same copy of esprima, which is just stupid. we could just fork each plugin and maintain them ourselves. we're also waiting on some plugins, and it might be easier for us to create them ourselves.
- increase the semver range and pin here in ecstacy
- don't depend on esprima and supply esprima/acorn here
- integration test all the plugins together

i'm not too keen on maintaining these plugins though. if anyone is interested in helping... @Swatinem

**Comment by Swatinem** [comment]
Meh, forking the plugins would be a big maintenance burden.
I think that should rather be solved upstream. I mean why do all those plugins pin outdated versions, and completely different versions altogether. Most are still on 0.5.\* of recast, and npm is annoying the hell out of me anyway because of that.
Not sure how receptive upstream is to the philosophy to require the users to provide esprima/recast themselves.

**Comment by jonathanong** [comment]
feel free to open issues upstream. i'll probably do that eventually once i figure out everything else

**Comment by jonathanong** [comment]
meh. just gonna open a bunch of issues later
